if not get_option('simple-dbuscall').disabled()
  subdir('simple-dbuscall')
endif

if not get_option('use-systemd1').disabled()
  subdir('use-systemd1')
endif

if not get_option('emit-signal').disabled()
  subdir('emit-signal')
endif

if not get_option('list-users').disabled()
  subdir('list-users')
endif

if not get_option('coroutine-example').disabled()
  subdir('coroutine-example')
endif

if not get_option('asio-example').disabled()
  subdir('asio-example')
endif

if not get_option('register-property').disabled()
  subdir('register-property')
endif

if not get_option('get-all-properties').disabled()
  subdir('get-all-properties')
endif